package com.darkfalcon.java.message;

public enum Opcode {
	CONNECT, DISCONNECT, IDENTIFY, VALIDATE_SYN, VALIDATE_ACK, VALIDATE_CLOSE, ACKNOLEDGED, REGISTER, SEND_MESSAGE, SEND_GROUPS, SEND_GROUPMEMBERS 
}
